/**
 * Public Portfolio Manager portfolio renderer.
 *
 * This file intentionally follows the same link-building behaviour used by the
 * Sandery.Dev portfolio script:
 * - project and repository URLs are normalised before validation;
 * - repository provider detection is handled separately from URL safety;
 * - a valid but unknown repository provider falls back to the generic Git icon.
 *
 * Portfolio Manager then layers its additional features on top:
 * - SQLite-backed/generated technology catalogue support;
 * - grouped technology stack rendering;
 * - OS/platform pins;
 * - public visibility filtering;
 * - search/year/technology filters.
 */
document.addEventListener("DOMContentLoaded", () => {
    const projectsContainer = document.getElementById("projects");
    const searchFilter = document.getElementById("portfolioSearchFilter");
    const yearFilter = document.getElementById("portfolioYearFilter");
    const techFilter = document.getElementById("portfolioTechFilter");
    const resetButton = document.getElementById("portfolioResetFilters");
    const filterSummary = document.getElementById("portfolioFilterSummary");

    /*
     * Exit early on pages that do not contain the portfolio grid.
     * This lets meta.php safely load this script globally if needed.
     */
    if (!projectsContainer) {
        return;
    }

    let allPortfolioProjects = [];

    /*
     * These values are generated by src/inc/tech-catalogue.js.php.
     * Fallbacks are kept so the page does not hard-crash if the catalogue
     * script is temporarily unavailable during development.
     */
    const techCategories = window.portfolioManagerTechCategories || {
        misc: "Other / Misc",
    };

    const techCatalogue = window.portfolioManagerTechCatalogue || {};
    const techLabelToKey = window.portfolioManagerTechLabelToKey || {};

    /*
     * OS/platform icons are still intentionally separate from the technology
     * catalogue because they answer "where does this project run?" rather than
     * "what was this project built with?"
     */
    const osIconMap = {
        Web: "src/icons/os/web.png",
        Windows: "src/icons/os/windows.png",
        macOS: "src/icons/os/apple.png",
        iOS: "src/icons/os/ios.png",
        Linux: "src/icons/os/linux.png",
        Android: "src/icons/os/android.svg",
        RaspberryPi: "src/icons/os/rpi.png",
        "Raspberry Pi": "src/icons/os/rpi.png",
    };

    /**
     * Escapes unsafe characters before inserting a value into generated HTML.
     *
     * @param {unknown} value Raw value from projects.json.
     * @returns {string} HTML-safe string.
     */
    function escapeHTML(value) {
        return String(value ?? "").replace(/[&<>"']/g, character => ({
            "&": "&amp;",
            "<": "&lt;",
            ">": "&gt;",
            '"': "&quot;",
            "'": "&#039;",
        }[character]));
    }

    /**
     * Normalises an external URL into an absolute URL before validation.
     *
     * This mirrors the important Sandery.Dev behaviour where a project link
     * such as "github.com/user/repo" is accepted and converted to
     * "https://github.com/user/repo" before the anchor is rendered.
     *
     * @param {string} url Raw project/repository URL.
     * @returns {string} Absolute http/https URL, or an empty string when invalid.
     */
    function normaliseExternalHref(url) {
        const rawUrl = String(url || "").trim();

        if (!rawUrl) {
            return "";
        }

        /*
         * If the user already supplied a protocol, keep it. Otherwise assume
         * HTTPS, which is the safest default for public portfolio links.
         */
        const candidate = /^[a-z][a-z0-9+.-]*:\/\//i.test(rawUrl)
            ? rawUrl
            : `https://${rawUrl}`;

        try {
            const parsed = new URL(candidate);

            if (!["http:", "https:"].includes(parsed.protocol)) {
                return "";
            }

            return parsed.href;
        } catch {
            return "";
        }
    }

    /**
     * Converts a technology label to a lookup-friendly key.
     *
     * This supports older projects.json records that store human-readable labels
     * instead of the generated catalogue key.
     *
     * @param {string} label Technology label such as "Node.js" or "C#".
     * @returns {string} Stable lookup key.
     */
    function techKey(label) {
        return String(label)
            .toLowerCase()
            .trim()
            .replace(/#/g, "sharp")
            .replace(/\+/g, "plus")
            .replace(/[.\s-]/g, "")
            .replace(/[^a-z0-9_]/g, "");
    }

    /**
     * Finds a catalogue entry from a visible label or stored key.
     *
     * @param {string} label Technology label from projects.json.
     * @returns {{label:string,category:string,icon:string}|null} Catalogue item or null.
     */
    function catalogueEntryForTech(label) {
        const rawLabel = String(label || "");
        const key = techLabelToKey[rawLabel] || techLabelToKey[techKey(rawLabel)] || techKey(rawLabel);

        return techCatalogue[key] || null;
    }

    /**
     * Looks up the SVG/PNG icon path for a technology label.
     *
     * @param {string} label Technology label.
     * @returns {string|null} Icon path when available.
     */
    function iconForTech(label) {
        const entry = catalogueEntryForTech(label);

        if (entry?.icon) {
            return entry.icon;
        }

        /*
         * Legacy fallback. Older Portfolio Manager/Sandery.Dev builds exposed a
         * flat techIcons object. This keeps old deployments tolerant during
         * staged migration, but the generated catalogue is the preferred source.
         */
        if (typeof techIcons !== "undefined") {
            return techIcons[label] || null;
        }

        return null;
    }

    /**
     * Converts old flat arrays and newer grouped tech objects into grouped data.
     *
     * @param {unknown} tech Technology data from a project record.
     * @returns {Record<string, string[]>} Technology labels grouped by category.
     */
    function normaliseTech(tech) {
        const grouped = Object.fromEntries(Object.keys(techCategories).map(category => [category, []]));

        if (Array.isArray(tech)) {
            tech.forEach(item => {
                const rawLabel = String(item);
                const entry = catalogueEntryForTech(rawLabel);
                const category = entry?.category && grouped[entry.category] ? entry.category : "misc";

                grouped[category].push(entry?.label || rawLabel);
            });
        } else if (tech && typeof tech === "object") {
            Object.keys(grouped).forEach(category => {
                grouped[category] = Array.isArray(tech[category])
                    ? tech[category].map(String).filter(Boolean)
                    : [];
            });
        }

        Object.keys(grouped).forEach(category => {
            grouped[category] = [...new Set(grouped[category])].sort((a, b) => a.localeCompare(b));
        });

        return grouped;
    }

    /**
     * Flattens a project's technology labels for filtering/searching.
     *
     * @param {object} project Project record.
     * @returns {string[]} Flat technology labels.
     */
    function flatTech(project) {
        return Object.values(normaliseTech(project.tech)).flat();
    }

    /**
     * Formats a project date as "Month Year".
     *
     * @param {string} dateValue ISO-style date string.
     * @returns {string} Formatted date or an empty string.
     */
    function formatProjectDate(dateValue) {
        if (!dateValue) {
            return "";
        }

        const date = new Date(dateValue);

        if (Number.isNaN(date.getTime())) {
            return "";
        }

        return new Intl.DateTimeFormat("en-AU", {
            month: "long",
            year: "numeric",
        }).format(date);
    }

    /**
     * Extracts the calendar year from a project record.
     *
     * @param {object} project Project record.
     * @returns {string} Project year or an empty string.
     */
    function getProjectYear(project) {
        if (!project?.date) {
            return "";
        }

        const date = new Date(project.date);

        if (Number.isNaN(date.getTime())) {
            return "";
        }

        return String(date.getFullYear());
    }

    /**
     * Checks whether a project should be visible to public users.
     *
     * @param {object} project Project record.
     * @returns {boolean} True when the project should be rendered.
     */
    function isProjectVisible(project) {
        return project.is_visible !== false;
    }

    /**
     * Builds a safe anchor used by the project card icon links.
     *
     * @param {string} url Link URL.
     * @param {string} className CSS class list for the icon.
     * @param {string} label Accessible label/title.
     * @returns {string} Anchor HTML or an empty string.
     */
    function buildProjectLink(url, className, label) {
        const cleanUrl = normaliseExternalHref(url);

        if (!cleanUrl) {
            return "";
        }

        return `
            <a
                class="${className}"
                href="${escapeHTML(cleanUrl)}"
                target="_blank"
                rel="noopener noreferrer"
                aria-label="${escapeHTML(label)}"
                title="${escapeHTML(label)}"
            ></a>
        `;
    }

    /**
     * Detects a repository provider using the shared helper when available.
     *
     * The shared helper is defined in src/js/repo-providers.js and should be
     * loaded before this file. A local fallback keeps the public renderer from
     * failing if the helper is missing during development.
     *
     * @param {string} repoUrl Repository URL.
     * @returns {{key:string,label:string}|null} Provider metadata or null.
     */
    function detectRepoProvider(repoUrl) {
        if (typeof window.pmDetectRepoProvider === "function") {
            return window.pmDetectRepoProvider(repoUrl, { loose: false });
        }

        /*
         * Development fallback only. The canonical provider list should live in
         * src/inc/repo-providers.js.php and be consumed by pmDetectRepoProvider.
         */
        const value = String(repoUrl || "").toLowerCase();

        if (!value) {
            return null;
        }

        const fallbackProviders = [
            { key: "github", label: "GitHub", patterns: ["github.com"] },
            { key: "gitlab", label: "GitLab", patterns: ["gitlab.com"] },
            { key: "bitbucket", label: "Bitbucket", patterns: ["bitbucket.org"] },
            { key: "azure", label: "Azure Repos", patterns: ["dev.azure.com", "visualstudio.com", "ssh.dev.azure.com"] },
            { key: "codeberg", label: "Codeberg", patterns: ["codeberg.org"] },
            { key: "gitea", label: "Gitea", patterns: ["gitea.com", "try.gitea.io", "gitea.io"] },
            { key: "sourcehut", label: "SourceHut", patterns: ["sr.ht", "git.sr.ht", "hg.sr.ht"] },
        ];

        try {
            const normalisedUrl = value.includes("://") ? value : `https://${value}`;
            const parsedUrl = new URL(normalisedUrl);
            const searchable = `${parsedUrl.hostname}${parsedUrl.pathname}`.toLowerCase();

            return fallbackProviders.find(provider => provider.patterns.some(pattern => searchable.includes(pattern))) || null;
        } catch {
            return fallbackProviders.find(provider => provider.patterns.some(pattern => value.includes(pattern))) || null;
        }
    }

    /**
     * Builds the repository link with a provider-specific icon class.
     *
     * Known providers receive their specific icon class. Unknown but valid
     * repository URLs fall back to the generic Git icon instead of disappearing.
     *
     * @param {object} project Project record.
     * @returns {string} Repository anchor HTML or an empty string.
     */
    function buildRepoLink(project) {
        const repoUrl = project.reporef || project.githubref || "";

        if (!repoUrl) {
            return "";
        }

        const provider = detectRepoProvider(repoUrl) || { key: "git", label: "Git" };

        return buildProjectLink(
            repoUrl,
            `project-repo repo-provider-${provider.key}`,
            `Open ${provider.label} repository`
        );
    }

    /**
     * Builds OS/platform pins shown under a project description.
     *
     * @param {object} project Project record.
     * @returns {string} OS pin block HTML or an empty string.
     */
    function buildOsPins(project) {
        const osList = Array.isArray(project.os) ? project.os.filter(Boolean) : [];

        if (osList.length === 0) {
            return "";
        }

        const pins = osList.map(osName => {
            const iconPath = osIconMap[osName] || "src/icons/unknown.svg";

            return `
                <span class="project-os-pin" title="${escapeHTML(osName)}">
                    <img src="${escapeHTML(iconPath)}" alt="">
                    <span>${escapeHTML(osName)}</span>
                </span>
            `;
        }).join("");

        return `
            <div class="project-os-block" aria-label="Supported operating systems">
                ${pins}
            </div>
        `;
    }

    /**
     * Builds a grouped technology stack for the project card.
     *
     * @param {object} project Project record.
     * @returns {string} Technology stack HTML.
     */
    function buildTechStack(project) {
        const grouped = normaliseTech(project.tech);
        const groups = Object.entries(grouped).filter(([, items]) => items.length > 0);

        if (groups.length === 0) {
            return "";
        }

        return groups.map(([category, items]) => {
            const techItems = items.map(item => {
                const icon = iconForTech(item);

                if (icon) {
                    return `<img class="techimg" src="${escapeHTML(icon)}" title="${escapeHTML(item)}" alt="${escapeHTML(item)}">`;
                }

                return `<em>${escapeHTML(item)}</em>`;
            }).join("");

            return `
                <div class="tech-group">
                    <strong>${escapeHTML(techCategories[category] || category)}</strong>
                    <span>${techItems}</span>
                </div>
            `;
        }).join("");
    }

    /**
     * Returns the unique project years available for the filter dropdown.
     *
     * @param {Array<object>} projects Project records.
     * @returns {string[]} Descending list of years.
     */
    function getAvailableYears(projects) {
        return [...new Set(projects.map(project => getProjectYear(project)).filter(Boolean))]
            .sort((a, b) => Number(b) - Number(a));
    }

    /**
     * Returns the unique technology labels available for the filter dropdown.
     *
     * @param {Array<object>} projects Project records.
     * @returns {string[]} Alphabetical technology labels.
     */
    function getAvailableTech(projects) {
        return [...new Set(projects.flatMap(flatTech))].sort((a, b) => a.localeCompare(b));
    }

    /**
     * Populates portfolio filter dropdowns from the public project list.
     *
     * @param {Array<object>} projects Public project records.
     * @returns {void}
     */
    function populatePortfolioFilters(projects) {
        if (!yearFilter || !techFilter) {
            return;
        }

        yearFilter.innerHTML = `<option value="all">All years</option>`;
        techFilter.innerHTML = `<option value="all">All tech</option>`;

        getAvailableYears(projects).forEach(year => {
            yearFilter.appendChild(new Option(year, year));
        });

        getAvailableTech(projects).forEach(tech => {
            techFilter.appendChild(new Option(tech, tech));
        });
    }

    /**
     * Applies active search/year/technology filters.
     *
     * @returns {Array<object>} Filtered project records.
     */
    function getFilteredPortfolioProjects() {
        const search = String(searchFilter?.value || "").trim().toLowerCase();
        const selectedYear = yearFilter?.value || "all";
        const selectedTech = techFilter?.value || "all";

        return allPortfolioProjects.filter(project => {
            const projectYear = getProjectYear(project);
            const projectTech = flatTech(project);
            const searchableText = `${project.title || ""} ${project.overview || ""} ${projectTech.join(" ")}`.toLowerCase();

            const searchMatches = search === "" || searchableText.includes(search);
            const yearMatches = selectedYear === "all" || projectYear === selectedYear;
            const techMatches = selectedTech === "all" || projectTech.includes(selectedTech);

            return searchMatches && yearMatches && techMatches;
        });
    }

    /**
     * Updates the small summary label at the right side of the filter panel.
     *
     * @param {Array<object>} filteredProjects Filtered public projects.
     * @returns {void}
     */
    function updatePortfolioFilterSummary(filteredProjects) {
        if (!filterSummary) {
            return;
        }

        const total = allPortfolioProjects.length;
        const shown = filteredProjects.length;

        if (total === 0) {
            filterSummary.textContent = "No public projects available.";
            return;
        }

        if (shown === total) {
            filterSummary.textContent = `Showing all ${total} project${total === 1 ? "" : "s"}.`;
            return;
        }

        filterSummary.textContent = `Showing ${shown} of ${total} project${total === 1 ? "" : "s"}.`;
    }

    /**
     * Renders project cards into the public portfolio grid.
     *
     * @param {Array<object>} projects Project records to render.
     * @returns {void}
     */
    function renderProjects(projects) {
        const sortedProjects = [...projects].sort((a, b) => new Date(b.date || 0) - new Date(a.date || 0));

        projectsContainer.innerHTML = "";
        updatePortfolioFilterSummary(sortedProjects);

        if (sortedProjects.length === 0) {
            projectsContainer.innerHTML = `
                <article class="portfolio-empty-state">
                    <h2>No matching projects</h2>
                    <p>No public portfolio projects match the selected filters.</p>
                </article>
            `;
            return;
        }

        sortedProjects.forEach((project, index) => {
            const div = document.createElement("div");
            div.classList.add("project");

            const externalLinkHTML = project.linkref
                ? buildProjectLink(project.linkref, "site-link", "Open project website")
                : "";

            const repoLinkHTML = buildRepoLink(project);
            const osPinsHTML = buildOsPins(project);
            const formattedDate = formatProjectDate(project.date);
            const techStackHTML = buildTechStack(project);

            div.innerHTML = `
                <div class="project-box">
                    <div class="project-container"></div>

                    <div class="project-details">
                        <div class="project-name">${escapeHTML(project.title || "Untitled Project")}</div>
                        <div class="project-date">${formattedDate ? `(${escapeHTML(formattedDate)})` : ""}</div>
                    </div>

                    <div class="project-links">
                        ${externalLinkHTML}
                        ${repoLinkHTML}
                    </div>

                    <div class="project-overview">${escapeHTML(project.overview || "")}</div>

                    

                    <div class="stack">
                        ${techStackHTML}
                    </div>
                    ${osPinsHTML}
                </div>
            `;

            div.querySelector(".project-box")?.style.setProperty("--i", index);
            projectsContainer.appendChild(div);
        });
    }

    /**
     * Applies the current filter controls and refreshes the cards.
     *
     * @returns {void}
     */
    function applyPortfolioFilters() {
        renderProjects(getFilteredPortfolioProjects());
    }

    /**
     * Clears all filter controls and restores the full public project list.
     *
     * @returns {void}
     */
    function resetPortfolioFilters() {
        if (searchFilter) {
            searchFilter.value = "";
        }

        if (yearFilter) {
            yearFilter.value = "all";
        }

        if (techFilter) {
            techFilter.value = "all";
        }

        renderProjects(allPortfolioProjects);
    }

    /**
     * Attaches filter control events after the page is ready.
     *
     * @returns {void}
     */
    function bindPortfolioFilterEvents() {
        searchFilter?.addEventListener("input", applyPortfolioFilters);
        yearFilter?.addEventListener("change", applyPortfolioFilters);
        techFilter?.addEventListener("change", applyPortfolioFilters);
        resetButton?.addEventListener("click", resetPortfolioFilters);
    }

    fetch(`src/js/projects.json?ts=${Date.now()}`, { cache: "no-store" })
        .then(response => {
            if (!response.ok) {
                throw new Error(`Failed to load projects.json: ${response.status}`);
            }

            return response.json();
        })
        .then(projects => {
            if (!Array.isArray(projects)) {
                throw new Error("projects.json did not return an array.");
            }

            allPortfolioProjects = projects.filter(isProjectVisible);

            populatePortfolioFilters(allPortfolioProjects);
            bindPortfolioFilterEvents();
            renderProjects(allPortfolioProjects);
        })
        .catch(error => {
            console.error("Failed to load projects.json:", error);

            projectsContainer.innerHTML = `
                <div class="project-box">
                    <h2>Portfolio unavailable</h2>
                    <p class="project-overview">
                        The portfolio data could not be loaded right now.
                    </p>
                </div>
            `;
        });
});
