const techIcons = {
    ".Net": "src/icons/.NET.svg",
    "Ajax": "src/icons/Ajax.svg",
    "Angular": "src/icons/Angular.svg",
    "Assembly": "src/icons/Assembly.svg",
    "AWS": "src/icons/AWS.png",
    "Bootstrap": "src/icons/Bootstrap.svg",
    "Bun": "src/icons/Bun.svg",
    "C#": "src/icons/C Sharp.svg",
    "C": "src/icons/C.svg",
    "C++": "src/icons/C++.svg",
    "CSS": "src/icons/CSS.svg",
    "Docker": "src/icons/Docker.svg",
    "HTML": "src/icons/HTML.svg",
    "Javascript": "src/icons/Javascript.svg",
    "jQuery": "src/icons/jQuery.svg",
    "JSON": "src/icons/JSON.svg",
    "Lua":  "src/icons/Lua.svg",
    "MongoDB":  "src/icons/MongoDB.svg",
    "MySQL": "src/icons/MySQL.svg",
    "NodeJS": "src/icons/NodeJS.svg",
    "NPM": "src/icons/NPM.svg",
    "PHP": "src/icons/PHP.svg",
    "PostgreSQL": "src/icons/PostgreSQL.svg",
    "Python": "src/icons/Python.svg",
    "RAILS": "src/icons/RubyOnRails.svg",
    "React": "src/icons/React.svg",
    "Ruby": "src/icons/Ruby.svg",
    "Rust": "src/icons/Rust.webp",
    "Selenium": "src/icons/Selenium.svg",
    "ShadCN": "src/icons/ShadCN.png",
    "SQLite": "src/icons/SQLite.svg",
    "TailwindCSS":"src/icons/TailwindCSS.svg",
    "Typescript": "src/icons/Typescript.svg",
};